version: "3"
services:

  database:
    image: postgres:14.12
    environment:
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
    - 5432:5432

  app:
    build:
      context: ./
      dockerfile: pastebin/Dockerfile
    command: flask --app pastebin/resources/ run --port 5000 --host 0.0.0.0
    ports:
    - 5000:5000
    depends_on:
    - database
