version: "3"
services:

  server:
    build:
      context: ".."
      dockerfile: Docker/server.Dockerfile
    ports:
    - "80:80"
    depends_on:
    - api
  
  api:
    build:
      context: ".."
      dockerfile: Docker/api.Dockerfile
    depends_on:
    - database
    - hashcache
  
  generator:
    build:
      context: ".."
      dockerfile: Docker/generator.Dockerfile
    depends_on:
    - hashcache
  
  hashcache:
    image: redis
    ports:
      - "${HASH_CACHE_PORT}:${HASH_CACHE_PORT}"
    volumes:
      - ../config/hashcache.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  
  database:
    image: postgres:14.12
    environment:
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
    - 5432:5432
