version: "3"
services:

  server:
    build:
      context: ".."
      dockerfile: Docker/server.Dockerfile
    ports:
    - "80:80"
    depends_on:
    - api
  
  api:
    build:
      context: ".."
      dockerfile: Docker/api.Dockerfile
    depends_on:
    - database
    - hashcache
    - textcache
    - metadatacache
    - autodelete
  
  autodelete:
    build:
      context: ".."
      dockerfile: Docker/autodelete.Dockerfile
    depends_on:
    - broker
    - database
    - hashcache
    - textcache
    - metadatacache
  
  generator:
    build:
      context: ".."
      dockerfile: Docker/generator.Dockerfile
    depends_on:
    - hashcache
    - sequence
  
  hashcache:
    image: redis:7.0.15-alpine
    ports:
      - "${HASH_CACHE_PORT}:${HASH_CACHE_PORT}"
    volumes:
      - ../config/hashcache.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  
  textcache:
    image: redis:7.0.15-alpine
    ports:
      - "${TEXT_CACHE_PORT}:${TEXT_CACHE_PORT}"
    volumes:
      - ../config/textcache.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  
  metadatacache:
    image: redis:7.0.15-alpine
    ports:
      - "${METADATA_CACHE_PORT}:${METADATA_CACHE_PORT}"
    volumes:
      - ../config/metadatacache.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  
  sequence:
    image: postgres:14.12
    environment:
    - POSTGRES_DB=${SEQUENCE_DB}
    - POSTGRES_USER=${SEQUENCE_USER}
    - POSTGRES_PASSWORD=${SEQUENCE_PASSWORD}
    ports:
    - 5433:5432
  
  database:
    image: postgres:14.12
    environment:
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
    - 5432:5432

  broker:
    image: rabbitmq:3.13.3
    ports:
    - 5672:5672
